---

apiVersion: v1
kind: Service

metadata:
  name: ingress-nodeports
  namespace: istio-system

spec:
  type: NodePort
  selector:
    istio: ingressgateway
  ports:
    - name: tls
      port: 30443
      targetPort: 15443
      nodePort: 30443
