---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: frpc
  namespace: gateway
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.frp: semver:~0.26

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: frpc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frpc
    spec:
      containers:
        - name: frp
          image: stevenxie/frp:0.26.0
          command: ["frpc"]
          args:
            - -c
            - frpc.ini
          envFrom:
            - secretRef:
                name: frpc
          volumeMounts:
            - name: config
              mountPath: /etc/frp
          resources:
            requests:
              cpu: 1m
              memory: 5Mi
            limits:
              cpu: 75m
              memory: 75Mi
      volumes:
        - name: config
          configMap:
            name: frpc

---

apiVersion: v1
kind: ConfigMap

metadata:
  name: frpc
  namespace: gateway

data:
  frpc.ini: |
    [common]
    server_addr = frps.stevenxie.me
    server_port = 30070
    tls_enable = true
    token = {{ .Envs.TOKEN }}

    [ingress]
    type = tcp
    local_ip = istio-ingressgateway.istio-system.svc.cluster.local
    local_port = 80
    remote_port = 8000
    use_encryption = true
    use_compression = true

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret

metadata:
  name: frpc
  namespace: gateway

spec:
  encryptedData:
    TOKEN: AgBlbCndpvHrx1w+e1ZfHfqQUlHPeF11qvYVWF2xKU9DUPc8GPhTg5JXshk2XFFm5Z1m+uu228SlJw49KoSC5Dk9a9s4VouACVp/3BcGilta2iMSK9VCgrefaTxIWbEm4xhFNzwup3tff6Y9YmWOZ4lJ9d6CuhdPyy8nwuPv+LkyZzLf/Y1ZUWJZBjSQ4na8j0JiWk30aJI/tY2YALrstcoEaBvUgnS4OaKMNyqY16JKjXP4Kx21doBEBWIRvPQE65+k5tanGXtK+eQ+yKv/Ag2FHyCfKg/mI/S0IqgYBHjwIYNoK3hZOYXh0Z80FrvZeU9IWR3OqPVMe2UG2lW0CgZKXnvSuPEMSZAD8TVc9tkMxoY8ohFHN3z4iSBxYUTgaRppm8hyZZuJ3SkIIdyoKEcVN6FcwjmnsKmRExR5xVvQ3G5i0LruXxR9D21p0Z1ED4t0fV+a2oBJTJqhHHDZuE/OdVB0nBq2TtUHW51hSPOE77u63EoVDx2uuwxjcI3LB2toRR8zNkDgFJ43E0hWCOHVJbu1rbnbExNxBYqb1acqJobNqTfCzpsModvEohMFHxgEINbYsDuWCSg/YBzl8qz80QLRMi4dZQbzNkfSwPTNegX51NSZMQmyeELUJgxQRz+Qdry6/P3XRRPHAeGVCKSy8tS7uXlTruvECMbO3+ZmPW2Z8SucncV/t2pAFmYKGfGV0IhMIR8z2xPB0IDMCu41bOTFuNlPAW8jSIGXo3s1ehTFYwe4j73lbejgADaJfmpnp3paYNCKiiNgEKDw9cle
